# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/case_transform2/all/case_transform2.rbi
#
# case_transform2-1.1.1

module CaseTransform2
  def self.camel(value); end
  def self.camel_cache; end
  def self.camel_lower(value); end
  def self.camel_lower_cache; end
  def self.dash(value); end
  def self.dash_cache; end
  def self.hash_ext; end
  def self.string_ext; end
  def self.unaltered(value); end
  def self.underscore(value); end
  def self.underscore_cache; end
end
class CaseTransform2::HashExt
  def _deep_transform_keys_in_object!(object, &block); end
  def deep_transform_keys!(object, &block); end
end
class CaseTransform2::StringExt
  def camelize(string, first_letter = nil); end
  def dasherize(string); end
  def underscore(string); end
end
