# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dry-core/all/dry-core.rbi
#
# dry-core-0.7.1

module Dry
  def self.Equalizer(*keys, **options); end
end
module Dry::Core
end
module Dry::Core::Constants
  def self.included(base); end
end
class Dry::Core::InvalidClassAttributeValue < StandardError
  def initialize(name, value); end
end
module Dry::Core::ClassAttributes
  def defines(*args, type: nil, coerce: nil); end
  include Dry::Core::Constants
end
class Dry::Core::Equalizer < Module
  def define_cmp_method; end
  def define_hash_method(immutable:); end
  def define_inspect_method; end
  def define_methods(inspect: nil, immutable: nil); end
  def included(descendant); end
  def initialize(*keys, **options); end
end
module Dry::Core::Equalizer::Methods
  def ==(other); end
  def eql?(other); end
end
module Dry::Core::Deprecations
  def self.[](tag); end
  def self.announce(name, msg, tag: nil, uplevel: nil); end
  def self.deprecated_name_message(old, new = nil, msg = nil); end
  def self.deprecation_message(name, msg); end
  def self.logger(output = nil); end
  def self.set_logger!(output = nil); end
  def self.warn(msg, tag: nil, uplevel: nil); end
end
class Dry::Core::Deprecations::Tagged < Module
  def extended(base); end
  def initialize(tag); end
end
module Dry::Core::Deprecations::Interface
  def deprecate(old_name, new_name = nil, message: nil); end
  def deprecate_class_method(old_name, new_name = nil, message: nil); end
  def deprecate_constant(constant_name, message: nil); end
  def deprecation_tag(tag = nil); end
  def warn(msg); end
end
