# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dry-configurable/all/dry-configurable.rbi
#
# dry-configurable-0.15.0

module Dry
end
module Dry::Configurable
  def enable_test_interface; end
  def self.extended(klass); end
  def self.included(klass); end
  extend Anonymous_Module_3
  extend Anonymous_Module_4
  extend Dry::Core::ClassAttributes
  include Dry::Core::Constants
end
module Anonymous_Module_3
  def inherited(klass); end
  def warn_on_setting_positional_default(value = nil); end
end
module Anonymous_Module_4
  def inherited(klass); end
  def warn_on_setting_constructor_block(value = nil); end
end
class Dry::Configurable::Error < StandardError
end
class Dry::Configurable::AlreadyIncluded < Dry::Configurable::Error
end
class Dry::Configurable::FrozenConfig < Dry::Configurable::Error
end
class Dry::Configurable::Config
  def [](name); end
  def []=(name, value); end
  def _resolved; end
  def _settings; end
  def finalize!(freeze_values: nil); end
  def initialize(settings); end
  def initialize_copy(source); end
  def method_missing(meth, *args); end
  def pristine; end
  def resolve(meth); end
  def respond_to_missing?(meth, include_private = nil); end
  def to_h; end
  def update(values); end
  def values; end
  include Anonymous_Dry_Core_Equalizer_5
  include Dry::Core::Equalizer::Methods
end
module Anonymous_Dry_Core_Equalizer_5
  def cmp?(comparator, other); end
  def hash; end
  def inspect; end
end
class Dry::Configurable::Setting
  def cloneable?; end
  def constructor; end
  def default; end
  def evaluate; end
  def evaluated?; end
  def finalize!(freeze_values: nil); end
  def initialize(name, input: nil, default: nil, **options); end
  def initialize_copy(source); end
  def input; end
  def input_defined?; end
  def name; end
  def nested(settings); end
  def options; end
  def pristine; end
  def reader?; end
  def self.cloneable_value?(value); end
  def value; end
  def with(new_opts); end
  def writer?(meth); end
  def writer_name; end
  include Anonymous_Dry_Core_Equalizer_6
  include Dry::Core::Equalizer::Methods
end
module Anonymous_Dry_Core_Equalizer_6
  def cmp?(comparator, other); end
  def hash; end
end
class Dry::Configurable::Setting::Nested < Dry::Configurable::Setting
  def constructor; end
  def pristine; end
end
class Dry::Configurable::Settings
  def <<(setting); end
  def [](name); end
  def each(&block); end
  def elements; end
  def finalize!(freeze_values: nil); end
  def initialize(elements = nil); end
  def initialize_copy(source); end
  def initialize_elements(elements); end
  def key?(name); end
  def keys; end
  def pristine; end
  include Anonymous_Dry_Core_Equalizer_7
  include Dry::Core::Equalizer::Methods
  include Enumerable
end
module Anonymous_Dry_Core_Equalizer_7
  def cmp?(comparator, other); end
  def hash; end
  def inspect; end
end
class Dry::Configurable::Compiler
  def call(ast); end
  def visit(node); end
  def visit_nested(node); end
  def visit_setting(node); end
end
class Dry::Configurable::DSL
  def ast; end
  def compiler; end
  def ensure_valid_options(options); end
  def initialize(&block); end
  def setting(name, default = nil, **options, &block); end
  def valid_and_invalid_options(options); end
end
module Dry::Configurable::Methods
  def configure(&block); end
  def finalize!(freeze_values: nil); end
end
module Dry::Configurable::ClassMethods
  def __config_dsl__; end
  def __config_reader__; end
  def _settings; end
  def config; end
  def inherited(subclass); end
  def setting(*args, **options, &block); end
  def settings; end
  include Dry::Configurable::Methods
end
module Dry::Configurable::Initializer
  def initialize(*arg0); end
end
module Dry::Configurable::InstanceMethods
  def config; end
  def finalize!(freeze_values: nil); end
  def initialize_copy(source); end
  include Dry::Configurable::Methods
end
module Dry::Configurable::TestInterface
  def reset_config; end
end
