# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/firebase_dynamic_link/all/firebase_dynamic_link.rbi
#
# firebase_dynamic_link-2.0.1

module FirebaseDynamicLink
  extend Dry::Configurable
  extend Dry::Configurable::ClassMethods
end
class FirebaseDynamicLink::InvalidConfig < StandardError
end
class FirebaseDynamicLink::ConnectionError < StandardError
end
class FirebaseDynamicLink::QuotaExceeded < StandardError
end
