language: ruby
rvm:
 - 2.2
 - 2.3
 - 2.4
 - 2.5
gemfile:
 - gemfiles/version_2017a.gemfile
 - gemfiles/version_2017b.gemfile
 - gemfiles/version_2018.gemfile
env:
  global:
    - CC_TEST_REPORTER_ID=22b531be7956bd878ec8ce211da98c483c9724eebc8eb72f99d064f00aa6e985
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - COVERAGE=1 bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT