name: Audit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@a1396b7d70b0d60cdf1d24584544a1f7024695b0
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Run security checks
        run: |
          bin/bundler-audit --update