name: Audit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@eae47962baca661befdfd24e4d6c34ade04858f7
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Run security checks
        run: |
          bin/bundler-audit --update