name: Audit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@9669f3ee51dc3f4eda8447ab696b3ab19a90d14b
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Run security checks
        run: |
          bin/bundler-audit --update