name: Audit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@ebaea52cb20fea395b0904125276395e37183dac
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Run security checks
        run: |
          bin/bundler-audit --update